package entities;
// Generated 6 juil. 2020 18:04:29 by Hibernate Tools 5.4.3.Final
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Column;
/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer")
public class Customer  {
	@Id
	@Column(name="basic_number")
	private Integer basicNumber;
	private String firstName;
	private String lastName;
	private String address;
	private String phoneNumber;
	private String sexe;
	private String identityNumber;
	private String identityType;
	private String email;

	public Customer() {
	}

	public Customer(String firstName, String lastName, String address, String phoneNumber, String sexe,
			String identityNumber, String identityType, String email) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.sexe = sexe;
		this.identityNumber = identityNumber;
		this.identityType = identityType;
		this.email = email;
	}

	public Integer getBasicNumber() {
		return this.basicNumber;
	}

	public void setBasicNumber(Integer basicNumber) {
		this.basicNumber = basicNumber;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	public String getIdentityNumber() {
		return this.identityNumber;
	}

	public void setIdentityNumber(String identityNumber) {
		this.identityNumber = identityNumber;
	}

	public String getIdentityType() {
		return this.identityType;
	}

	public void setIdentityType(String identityType) {
		this.identityType = identityType;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
