package entities;
// Generated 6 juil. 2020 18:04:29 by Hibernate Tools 5.4.3.Final
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Column;
import java.util.Date;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user")
public class User {
	@GeneratedValue
	@Id
	@Column(name="id")
	private Integer id;
	private String login;
	private String password;
	private String secondPassword;
	private int passwordStatus;
	private String firstName;
	private String lastName;
	private int basicNumber;
	private int accountStatus;
	private int nbFailedConnection;
	private Date creationDate;

	public User() {
	}

	public User(String login, String password, String secondPassword, int passwordStatus, String firstName,
			String lastName, int basicNumber, int accountStatus, int nbFailedConnection, Date creationDate) {
		this.login = login;
		this.password = password;
		this.secondPassword = secondPassword;
		this.passwordStatus = passwordStatus;
		this.firstName = firstName;
		this.lastName = lastName;
		this.basicNumber = basicNumber;
		this.accountStatus = accountStatus;
		this.nbFailedConnection = nbFailedConnection;
		this.creationDate = creationDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSecondPassword() {
		return this.secondPassword;
	}

	public void setSecondPassword(String secondPassword) {
		this.secondPassword = secondPassword;
	}

	public int getPasswordStatus() {
		return this.passwordStatus;
	}

	public void setPasswordStatus(int passwordStatus) {
		this.passwordStatus = passwordStatus;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public int getBasicNumber() {
		return this.basicNumber;
	}

	public void setBasicNumber(int basicNumber) {
		this.basicNumber = basicNumber;
	}

	public int getAccountStatus() {
		return this.accountStatus;
	}

	public void setAccountStatus(int accountStatus) {
		this.accountStatus = accountStatus;
	}

	public int getNbFailedConnection() {
		return this.nbFailedConnection;
	}

	public void setNbFailedConnection(int nbFailedConnection) {
		this.nbFailedConnection = nbFailedConnection;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
